-- =========================================================
-- P2P RENTAL PLATFORM
-- Supabase Auth + UUID based schema
-- =========================================================


-- =========================================================
-- STEP 1: DROP EXISTING APPLICATION TABLES
-- =========================================================

DROP TABLE IF EXISTS public.item_images CASCADE;
DROP TABLE IF EXISTS public.damage_reports CASCADE;
DROP TABLE IF EXISTS public.reviews CASCADE;
DROP TABLE IF EXISTS public.returns CASCADE;
DROP TABLE IF EXISTS public.payments CASCADE;
DROP TABLE IF EXISTS public.bookings CASCADE;
DROP TABLE IF EXISTS public.items CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;


-- =========================================================
-- STEP 2: USERS
-- Connected to Supabase Auth
-- =========================================================

CREATE TABLE public.users (
    user_id UUID PRIMARY KEY
        REFERENCES auth.users(id)
        ON DELETE CASCADE,

    name VARCHAR(100) NOT NULL,

    mobile VARCHAR(20) NOT NULL UNIQUE,

    location VARCHAR(255),

    rating NUMERIC(2,1) NOT NULL DEFAULT 0.0
        CHECK (rating >= 0 AND rating <= 5),

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- STEP 3: CATEGORIES
-- =========================================================

CREATE TABLE public.categories (
    cat_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    cat_name VARCHAR(100) NOT NULL UNIQUE,

    description TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- STEP 4: ITEMS
-- =========================================================

CREATE TABLE public.items (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    owner_id UUID NOT NULL,

    cat_id BIGINT NOT NULL,

    item_name VARCHAR(150) NOT NULL,

    description TEXT,

    location VARCHAR(255),

    condition VARCHAR(100),

    availability BOOLEAN NOT NULL DEFAULT TRUE,

    rental_price NUMERIC(10,2) NOT NULL
        CHECK (rental_price >= 0),

    security_deposit NUMERIC(10,2) NOT NULL DEFAULT 0
        CHECK (security_deposit >= 0),

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_item_owner
        FOREIGN KEY (owner_id)
        REFERENCES public.users(user_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_item_category
        FOREIGN KEY (cat_id)
        REFERENCES public.categories(cat_id)
        ON DELETE RESTRICT
);


-- =========================================================
-- STEP 5: BOOKINGS
-- =========================================================

CREATE TABLE public.bookings (
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    item_id BIGINT NOT NULL,

    renter_id UUID NOT NULL,

    lender_id UUID NOT NULL,

    start_time TIMESTAMPTZ NOT NULL,

    end_time TIMESTAMPTZ NOT NULL,

    price NUMERIC(10,2) NOT NULL
        CHECK (price >= 0),

    security_deposit NUMERIC(10,2) NOT NULL
        CHECK (security_deposit >= 0),

    status VARCHAR(30) NOT NULL DEFAULT 'BOOKED',

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_booking_item
        FOREIGN KEY (item_id)
        REFERENCES public.items(item_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_booking_renter
        FOREIGN KEY (renter_id)
        REFERENCES public.users(user_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_booking_lender
        FOREIGN KEY (lender_id)
        REFERENCES public.users(user_id)
        ON DELETE RESTRICT,

    CONSTRAINT check_booking_time
        CHECK (end_time > start_time),

    CONSTRAINT check_different_users
        CHECK (renter_id <> lender_id)
);


-- =========================================================
-- STEP 6: PAYMENTS
-- =========================================================

CREATE TABLE public.payments (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    booking_id BIGINT NOT NULL,

    amount NUMERIC(10,2) NOT NULL
        CHECK (amount >= 0),

    payment_type VARCHAR(30) NOT NULL
        CHECK (
            payment_type IN (
                'ADVANCE',
                'SECURITY_DEPOSIT',
                'REMAINING_AMOUNT',
                'DAMAGE_PAYMENT',
                'REFUND'
            )
        ),

    payment_method VARCHAR(30),

    transaction_id VARCHAR(255) UNIQUE,

    payment_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',

    payment_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_payment_booking
        FOREIGN KEY (booking_id)
        REFERENCES public.bookings(booking_id)
        ON DELETE RESTRICT
);


-- =========================================================
-- STEP 7: RETURNS
-- =========================================================

CREATE TABLE public.returns (
    return_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    booking_id BIGINT NOT NULL UNIQUE,

    return_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',

    condition VARCHAR(100),

    remarks TEXT,

    CONSTRAINT fk_return_booking
        FOREIGN KEY (booking_id)
        REFERENCES public.bookings(booking_id)
        ON DELETE RESTRICT
);


-- =========================================================
-- STEP 8: DAMAGE REPORTS
-- =========================================================

CREATE TABLE public.damage_reports (
    damage_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    booking_id BIGINT NOT NULL,

    damage_description TEXT NOT NULL,

    damage_cost NUMERIC(10,2) NOT NULL DEFAULT 0
        CHECK (damage_cost >= 0),

    image_url TEXT,

    status VARCHAR(30) NOT NULL DEFAULT 'REPORTED',

    reported_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_damage_booking
        FOREIGN KEY (booking_id)
        REFERENCES public.bookings(booking_id)
        ON DELETE RESTRICT
);


-- =========================================================
-- STEP 9: REVIEWS
-- =========================================================

CREATE TABLE public.reviews (
    review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    booking_id BIGINT NOT NULL UNIQUE,

    reviewer_id UUID NOT NULL,

    reviewee_id UUID NOT NULL,

    rating NUMERIC(2,1) NOT NULL
        CHECK (rating >= 1 AND rating <= 5),

    comment TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_review_booking
        FOREIGN KEY (booking_id)
        REFERENCES public.bookings(booking_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_review_reviewer
        FOREIGN KEY (reviewer_id)
        REFERENCES public.users(user_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_review_reviewee
        FOREIGN KEY (reviewee_id)
        REFERENCES public.users(user_id)
        ON DELETE RESTRICT,

    CONSTRAINT check_review_users
        CHECK (reviewer_id <> reviewee_id)
);


-- =========================================================
-- STEP 10: ITEM IMAGES
-- =========================================================

CREATE TABLE public.item_images (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    item_id BIGINT NOT NULL,

    image_url TEXT NOT NULL,

    is_primary BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_item_images_item
        FOREIGN KEY (item_id)
        REFERENCES public.items(item_id)
        ON DELETE CASCADE
);


-- =========================================================
-- STEP 11: INDEXES
-- =========================================================

CREATE INDEX idx_items_owner
    ON public.items(owner_id);

CREATE INDEX idx_items_category
    ON public.items(cat_id);

CREATE INDEX idx_items_availability
    ON public.items(availability);

CREATE INDEX idx_bookings_item
    ON public.bookings(item_id);

CREATE INDEX idx_bookings_renter
    ON public.bookings(renter_id);

CREATE INDEX idx_bookings_lender
    ON public.bookings(lender_id);

CREATE INDEX idx_payments_booking
    ON public.payments(booking_id);

CREATE INDEX idx_damage_reports_booking
    ON public.damage_reports(booking_id);

CREATE INDEX idx_reviews_reviewee
    ON public.reviews(reviewee_id);

CREATE INDEX idx_item_images_item
    ON public.item_images(item_id);

ALTER TABLE public.users
DROP CONSTRAINT users_user_id_fkey;

ALTER TABLE public.users
ADD CONSTRAINT users_user_id_fkey
FOREIGN KEY (user_id)
REFERENCES auth.users(id)
ON DELETE CASCADE;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    INSERT INTO public.users (
        user_id,
        name,
        mobile
    )
    VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data->>'name', 'User'),
        COALESCE(NEW.raw_user_meta_data->>'mobile', '')
    );

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created
ON auth.users;

CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.handle_new_user();

ALTER TABLE public.users
DROP CONSTRAINT users_user_id_fkey;

ALTER TABLE public.users
ADD CONSTRAINT users_user_id_fkey
FOREIGN KEY (user_id)
REFERENCES auth.users(id)
ON DELETE CASCADE;